const REGION_MAPPING = {
  EU: [
    "NG",
    "GB",
    "FR",
    "DE",
    "IT",
    "ES",
    "GH",
    "ZA",
    "KE",
    "EG",
    "MA",
    "TN",
    "SN",
    "CI",
    "CM",
    "UG",
    "RW",
    "ET",
    "TZ",
    "MZ",
    "AO",
    "ZM",
    "ZW",
    "BW",
    "NA",
    "IE",
    "PT",
    "BE",
    "NL",
    "LU",
    "CH",
    "AT",
    "SE",
    "NO",
    "DK",
    "FI",
    "PL",
    "CZ",
    "SK",
    "HU",
    "RO",
    "BG",
    "GR",
    "HR",
    "RS",
    "SI",
    "AL",
    "MT",
    "CY",
  ],

  APAC: [
    "CN",
    "JP",
    "KR",
    "IN",
    "AU",
    "NZ",
    "SG",
    "MY",
    "ID",
    "PH",
    "TH",
    "VN",
    "MM",
    "KH",
    "LA",
    "BN",
    "TW",
    "HK",
    "MO",
    "LK",
    "NP",
    "BD",
    "PK",
    "AF",
    "UZ",
    "KZ",
    "KG",
    "TJ",
    "TM",
    "MN",
    "BT",
    "MV",
    "FJ",
    "PG",
    "SB",
    "VU",
    "NC",
    "PF",
  ],

  US: [
    "US",
    "CA",
    "MX",
    "BR",
    "AR",
    "CL",
    "CO",
    "PE",
    "EC",
    "VE",
    "BO",
    "PY",
    "UY",
    "GY",
    "SR",
    "GF",
    "PA",
    "CR",
    "NI",
    "HN",
    "SV",
    "GT",
    "BZ",
    "CU",
    "DO",
    "HT",
    "PR",
    "JM",
    "BS",
    "BB",
    "TT",
    "LC",
    "VC",
    "GD",
    "AG",
    "DM",
    "KN",
    "TC",
    "VG",
    "AI",
  ],
};

const DOCUMENT_TYPES = {
  NG: ["NIN", "DL", "PP", "VC", "BVN"],
  GH: ["NID", "DL", "PP", "VC", "NHIS"],
  ZA: ["ID", "DL", "PP", "RC"],
  KE: ["ID", "DL", "PP", "AC"],
  EG: ["NID", "DL", "PP"],

  GB: ["DL", "PP", "RC", "NINO"],
  FR: ["CNI", "DL", "PP", "TS"],
  DE: ["PA", "DL", "PP", "ID"],
  IT: ["CIE", "DL", "PP", "CF"],
  ES: ["DNI", "DL", "PP", "NIE"],

  US: ["DL", "PP", "SSC", "SC", "MC"],
  CA: ["DL", "PP", "PR", "HC"],
  MX: ["INE", "DL", "PP", "RFC"],

  BR: ["RG", "CNH", "PP", "CPF"],
  AR: ["DNI", "DL", "PP", "CUIL"],
  CO: ["CC", "DL", "PP", "CE"],

  CN: ["SFZ", "DL", "PP", "HKB"], // China
  JP: ["MY", "DL", "PP", "RC"], // Japan
  IN: ["AA", "DL", "PP", "VC", "PAN"], // India
  SG: ["NRIC", "DL", "PP", "FIN"], // Singapore
  KR: ["RRC", "DL", "PP", "ARC"], // South Korea

  AU: ["DL", "PP", "MC", "KC"],
  NZ: ["DL", "PP", "BC", "CC"],
};

const DOCUMENT_TYPE_DESCRIPTIONS = {
  PP: "Passport",
  DL: "Driver's License",
  ID: "National ID Card",
  BC: "Birth Certificate",
  RC: "Residence Card",

  NIN: "National Identity Number Card",
  BVN: "Bank Verification Number Card",
  VC: "Voter's Card",

  NINO: "National Insurance Number Card",

  CNI: "Carte Nationale d'Identité",
  TS: "Titre de Séjour",

  PA: "Personalausweis",

  CIE: "Carta d'Identità Elettronica",
  CF: "Codice Fiscale",

  DNI: "Documento Nacional de Identidad",
  NIE: "Número de Identidad de Extranjero",

  SSC: "Social Security Card",
  SC: "State ID Card",
  MC: "Medicare Card",

  AA: "Aadhaar Card",
  PAN: "Permanent Account Number Card",

  SFZ: "Resident Identity Card",
  HKB: "Hukou Book",

  NRIC: "National Registration Identity Card",
  FIN: "Foreign Identification Number",

  RG: "Registro Geral",
  CNH: "Carteira Nacional de Habilitação",
  CPF: "Cadastro de Pessoas Físicas",

  INE: "Instituto Nacional Electoral Card",
  RFC: "Registro Federal de Contribuyentes",
};

const VALIDATION_RULES = {
  PP: {
    expiryRequired: true,
    ageCheck: true,
    photoRequired: true,
    mrzRequired: true,
    minAge: 0,
    maxAge: 100,
    expiryMinDays: 90,
    documentNumberFormat: /^[A-Z0-9]{6,12}$/,
    securityFeatures: ["UV", "MRZ", "HOLOGRAM"],
    requiredFields: [
      "surname",
      "givenNames",
      "dateOfBirth",
      "nationality",
      "documentNumber",
      "expiryDate",
    ],
  },
  DL: {
    expiryRequired: true,
    ageCheck: true,
    photoRequired: true,
    addressRequired: true,
    minAge: 16,
    maxAge: 100,
    expiryMinDays: 30,
    documentNumberFormat: /^[A-Z0-9]{4,20}$/,
    securityFeatures: ["BARCODE", "HOLOGRAM"],
    requiredFields: [
      "surname",
      "givenNames",
      "dateOfBirth",
      "address",
      "documentNumber",
      "expiryDate",
      "vehicleCategories",
    ],
  },
  ID: {
    expiryRequired: false,
    ageCheck: true,
    photoRequired: true,
    addressRequired: true,
    minAge: 0,
    maxAge: 100,
    documentNumberFormat: /^[A-Z0-9-]{4,20}$/,
    securityFeatures: ["HOLOGRAM", "BARCODE"],
    requiredFields: [
      "surname",
      "givenNames",
      "dateOfBirth",
      "nationality",
      "documentNumber",
    ],
  },

  NG: {
    NIN: {
      expiryRequired: false,
      ageCheck: true,
      photoRequired: true,
      minAge: 16,
      documentNumberFormat: /^\d{11}$/,
      securityFeatures: ["QR", "BARCODE"],
      requiredFields: [
        "surname",
        "givenNames",
        "dateOfBirth",
        "nationality",
        "documentNumber",
      ],
    },
    BVN: {
      expiryRequired: false,
      ageCheck: true,
      photoRequired: false,
      documentNumberFormat: /^\d{11}$/,
      requiredFields: [
        "surname",
        "givenNames",
        "dateOfBirth",
        "documentNumber",
      ],
    },
  },
  US: {
    SSC: {
      expiryRequired: false,
      ageCheck: false,
      photoRequired: false,
      documentNumberFormat: /^\d{3}-\d{2}-\d{4}$/,
      requiredFields: ["surname", "givenNames", "documentNumber"],
    },
  },
  GB: {
    NINO: {
      expiryRequired: false,
      ageCheck: true,
      photoRequired: false,
      minAge: 16,
      documentNumberFormat:
        /^[A-CEGHJ-PR-TW-Z]{1}[A-CEGHJ-NPR-TW-Z]{1}[0-9]{6}[A-D\s]$/,
      requiredFields: [
        "surname",
        "givenNames",
        "dateOfBirth",
        "documentNumber",
      ],
    },
  },
};

const SECURITY_FEATURE_REQUIREMENTS = {
  UV: {
    minConfidence: 0.8,
    requiredElements: ["UV_FIBERS", "UV_PORTRAIT"],
  },
  MRZ: {
    minConfidence: 0.9,
    checkDigitValidation: true,
  },
  HOLOGRAM: {
    minConfidence: 0.85,
    requiredElements: ["HOLOGRAPHIC_PORTRAIT", "KINEGRAM"],
  },
  BARCODE: {
    minConfidence: 0.95,
    validateContent: true,
    crossValidateWithOCR: true,
  },
  QR: {
    minConfidence: 0.95,
    validateContent: true,
    validateSignature: true,
  },
};

module.exports = {
  REGION_MAPPING,
  DOCUMENT_TYPES,
  DOCUMENT_TYPE_DESCRIPTIONS,
  VALIDATION_RULES,
  SECURITY_FEATURE_REQUIREMENTS,
};
